### ISSUE TITLE
a run from registry/update from registry plugin

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [prologic/autodock#2]
basic list of use-cases i came up with
- spin up a new instance from a private registry with a new  hostname/database/redis/...
- update a already running instance to a new version from the registry
- list running app instances
- stop a app instance
- discard a app instance including databases/...
##

**Comment by prologic** [comment]
Do you see it working something like this?

```#!bash
docker run -d -e [options form envvars] prologic/autodock-run <registry_image_uri>
```

That would solve the first part; and open up room for webhook(s) that could trigger the an update. Perhaps ``autodock-run`` could also keep "state" and a list of "services" it is managing to solve the
3rd and 4th items. Thoughts? I can see this as being a "good" way to quickly spin up a typical well defined webapp within the autodock supported infrastructure (load balancing, dns, etc)

**Comment by prologic** [comment]
Also what you've just described here has inspired me to write #3 which I think could be a nice way to do "continuous deployments"

**Comment by RonnyPfannschmidt** [comment]
for QA purposes its kind of important to have a very exact idea of whats running

I think direct commit hooks are a bad idea, deploy actions are way better (there should be CI before CD)

perhaps a small webapp with a list of the running containers
and availiable container updates/versions would be nice

PS: Manual testers get very unhappy if you replace the app under them when they do explorative testing

**Comment by prologic** [comment]
Ahh right; I see. So an ``autodock-deploy`` would work better as a trigger **after** CI; but not before :)

Re ``autodock-run`` -- Okay I think I get the idea behind this as well. Basically a way to "run" and "manage" containers/apps, their upgrade(s) and state?

**Comment by RonnyPfannschmidt** [comment]
thie idea is to have a simple container that listens for deploy actions of an app version, and either record as availiable update or do the update

so i can run the app in a manual update version for the qa and the demonstration version in autoupdate

**Comment by prologic** [comment]
Okay; if I prototype this up will the public docker hub be fine for now? I do believe all other private registries talk/use the same protocols/software anyway... So it *should* be trivial to support "private registry" too.

**Comment by prologic** [comment]
@RonnyPfannschmidt Was just thinking... (*dangeous I know!*) and I feel like coding before bed! What if we take this a step back a bit and write a plugin that monitors containers and their registry/upgrade status with the ability to upgrade them. It would be a simple JSON API that exposes what ``docker ps`` knows about with some "extra fields" (``version, available``) and an ``/upgrade/cid`` endpoint that would upgrade the named container.

**Comment by RonnyPfannschmidt** [comment]
how about 2 plugins

a) simple status overview
b) linking running containers to registries including listing updates

**Comment by prologic** [comment]
I'll try and do a) tonight for fun and see what you think :)

**Comment by RonnyPfannschmidt** [comment]
closing to get if off my plate on github
