### ISSUE TITLE
An API for autodock and plugins

### ISSUE THREAD

**Issue by prologic** [prologic/autodock#4]
For some of the reasons discussed in #2 and #3 I believe `autodock` itself should expose an internal-use API that other plugins can expose API functions to much like they already do for "listening to Docker Events" and "Accessing the Docker API".
##

**Comment by prologic** [comment]
This would make writing other plugins a bit easier as well as you could then start to "talk to" other plugins via a common unified API; for example ons use case:

*Remove a container from the ``autodock-hipache`` + ``hipache`` load balancer*:
```#!bash
curl -q -o - http://127.0.0.1:8331/hipache/remove/<cid>
```

Where ``<cid>`` is a Container ID to be removed that ahd ``-e VIRTUALHOST=`` where ``autodock-hipache`` previously added this container to the ``hipache`` load balancer.

**Comment by RonnyPfannschmidt** [comment]
idea: it might be more versatile to destroy a container and recreate it with a different configuration practically immediately than to include apis for modification of a container

**Comment by prologic** [comment]
What are you thinking here? I'm just thinking of a way to define a clear way to allow autodock plugins to define useful API(s).

**Comment by RonnyPfannschmidt** [comment]
instead of having an api to change state, it seems practical to simply destroy a container and remake it with a slightly different state

then plugins would listen to new container changes instead
so from my pvt the only "api" should scratch/remake containers, plugins would simply listen to events
and provide data about the state

**Comment by prologic** [comment]
The use-case specifically I'm talking about here may *bend* your "rules" as such; because in order to support "graceful" upgrades of a web container it's necessary to perform the following:

- Scale up to 2x the no. of existing web backends
- Pull down the latest images
- For each old container:
  - Remove form load balancer
  - Wait for connections to drain
  - Remove/Destroy the container
- Reorder the new containers for posterity.

I already have *most* of this more or less working in [autodock-upgrade](https://github.com/prologic/autodock-upgrade) -- So this is the very specific use-case being exposing an API where "some" state can be changed. But otherwise I agree with you that it should be possible to destroy containers and re-create them with new configuration -- but how would this be any difference to doing a ``docker rm -f ...`` followed by a ``docker run ...``?

**Comment by RonnyPfannschmidt** [comment]
i see what you mean, i dont see how that isnt just destroy/create

perhaps a better term would be "gracefull" destruction

an update would bascially be start a new container, gracefully remove a old one, repeat until done, then perhaps reorder

**Comment by prologic** [comment]
Yes I see where you're coming from too; "graceful destroy".

**Comment by RonnyPfannschmidt** [comment]
perhaps a lifecycle concept for containers and attached ressources is needed

**Comment by prologic** [comment]
How would you manage it; in a semi-automated way?

**Comment by RonnyPfannschmidt** [comment]
semi-automated

i would suggest set of statemachines, - putting a containr in a shuttung down state, having all plugins ack the shutdown, then disposing the container,

same for the startup

**Comment by prologic** [comment]
Hmm interesting; it's a shame we can't "intercept" Docker events and potentially stall them as such; effectively extending the Docker behaviour via events :)

**Comment by prologic** [comment]
So a ``autodock-lifecycle`` would definitely have to be managed via an "API Call" of some kind even if internally called; e.g:

```#!bash
curl -q -o - http://127.0.0.1:8331/lifecycle/terminate/<cid>
```

or

```#!bash
docker run --rm prologic/autodock-lifecycle terminate <cid>
```

Which would do what you described:

- fire a ``container_terminating(cid)`` event
- Give a chance for plugins to intercept/ack this

A "graceful destroy" plugin could intercept this; wait for connections to drain and then finally complete the container destroy.

**Comment by RonnyPfannschmidt** [comment]
i would view docker as part of the bigger statemachines, docker events can drive a higher level

i think docker events would fit nicely as part of a larger state graph
this is a tricky topic, expect to get it wrong 2-5 times :)

you will need a way to define how plugins will hook into transitions

**Comment by prologic** [comment]
Well plugins already obviously "hook in" to all known docker events right now; this is how [autodock-cron](https://github.com/prologic/autodock-cron), [autodock-hipache](https://github.com/prologic/autodock-hipache) and [autodock-logger](https://github.com/prologic/autodock-logger) all work :)

**Comment by RonnyPfannschmidt** [comment]
personally i dont care if a stategraph is layered on top of the docker one or if the docker one is used, i just want the tool to work ^^

**Comment by prologic** [comment]
:+1:

**Comment by prologic** [comment]
A Go plugin framework now exists and is implemented in: [autodock-logger](https://github.com/prologic/autodock-logger). It works; it could be improved upon but it's good enough for now.

I may replace the plugin architecture with [hashicorp/go-plugin](https://github.com/hashicorp/go-plugin) if there is enough interested in this as it supports plugins over RPC and is thereby language agnostic.
